### ISSUE TITLE
Subtyping and unique names

### ISSUE THREAD

**Issue by Horcrux7** [lars-t-hansen/moz-gc-experiments#7]
> Field names must be unique in the module; a useful trick to make this restriction bearable is to prepend the structure name to every field name along with a legal separator such as _ or .

The requirement of unique field names is not helpful for subtyping. I try to define the follow 2 types (main type and subtype):

```
(module (gc_feature_opt_in 3)
  (type $Abc (struct
    (field $Abc.a (mut i32))
    (field $Abc.b (mut i64))
  ))
  (type $Abc2 (struct
    (field $Abc.a (mut i32))
    (field $Abc.b (mut i64))
    (field $Abc2.c (mut f32))
  ))
)
```
This result in the follow error message:
```
SyntaxError: wasm text error: duplicate field name (must be unique in module)
```
With subtyping the field names should be identical because if I call a `struct.set` or `struct.get` I need to use the same names. I does does not know if the instance is a main type or a subtype.

**Comment by lars-t-hansen** [comment]
This is not actually a problem, because the field names are just symbolic names for offset values anyway - the underlying binary code doesn't use names, it just uses indices.  `$Abc.a` is 0, `$Abc.b` is 1, `$Abc2.c` is 2, etc.  There is absolutely no type checking on these field names; the following code is perfectly fine because `$Foo.x` and `$Bar.y` are just symbolic constants both meaning 0 for all struct types:

```
(module (gc_feature_opt_in 3)
  (type $Foo (field $Foo.x (mut i32)))
  (type $Bar (field $Bar.y f64))
  (func (param $p (ref $Foo)) (result i32)
    (struct.get $Foo $Bar.y)))
```

So what you want to do is this:

```
(module (gc_feature_opt_in 3)
  (type $Abc (struct
    (field $Abc.a (mut i32))
    (field $Abc.b (mut i64))
  ))
  (type $Abc2 (struct
    (field $Abc2.a (mut i32))
    (field $Abc2.b (mut i64))
    (field $Abc2.c (mut f32))
  ))
)
```

Now if you have a reference to a `$Abc` that may be a reference to a `$Abc2` you can still read its `a` and `b` fields using `$Abc.a` and `$Abc.b` as names.

**Comment by Horcrux7** [comment]
This would only work if the super class will ever declared. I use only index value in the mean time. I think like the other problems with WasmTextToBinary this will be an job for a volunteer.

**Comment by lars-t-hansen** [comment]
I don't know what you mean by "superclass" since there's no inheritance hierarchy here, only a prefix system, but the point is that you can't have a reference to `$Abc` if you haven't defined `$Abc`.  But if you haven't defined `$Abc` you have surely defined `$Abc2` and you can use its names, and every reference in your program will be `(ref $Abc2)` (since there is no `$Abc`).

But yes, for compiler writers that know what their layouts look like there is no sense in using the names, and the naming system was not defined for them - it was defined for people writing test cases by hand.

(There's really no bug here and nothing to fix; it is working as designed :-)
